#!/bin/sh

LDR_VER=`grep UBOOTVER= /dev/mtd0 | cut -d= -f2`
[ -z "${LDR_VER}" ] && LDR_VER=0.8.2

uci set system.@system[0].firmware_version=1.0.2
uci set system.@system[0].firmware_buildcode=2
uci set system.@system[0].dj310_firstboot=1

uci set system.@system[0].loader_version=v${LDR_VER}

uci commit system
