#!/bin/sh

. /lib/functions.sh

echo "==================" > /dev/console
echo "ACTION: " $ACTION > /dev/console
echo "SEEN: " $SEEN > /dev/console
echo "SUBSYSTEM: " $SUBSYSTEM > /dev/console
echo "BUTTON: "$BUTTON > /dev/console
echo "TYPE: " $TYPE > /dev/console
echo "SEQNUM: " $SEQNUM > /dev/console

case "$ACTION" in
pressed)
	return 5
;;
timeout)
	. /etc/diag.sh
	set_state failsafe
;;
released)
	if [ "$SEEN" -lt 1 ]
	then
		. /etc/diag.sh
		set_state pairing
		mosquitto_pub -t "ui/button/pairing"
	elif [ "$SEEN" -gt 5 ]
	then
		echo "SEEN: " $SEEN > /dev/console
	fi
;;
esac

return 0
