#!/bin/sh

. /lib/functions.sh
. /usr/share/libubox/jshn.sh

json_init
json_add_string event "button"
json_add_object "message"
json_add_string "button" "iot"
json_add_string "action" "$ACTION"
json_add_int "seen" "$SEEN"
json_add_int "seqnum" "$SEQNUM"
json_close_object

echo "$(json_dump)" > /dev/console

ubus send ubusipc.event "$(json_dump)"

return 0
