#!/bin/sh

. /lib/functions.sh

case "$ACTION" in
pressed)
	return 5
;;
timeout)
	. /etc/diag.sh
	set_state failsafe
;;
released)
	if [ "$SEEN" -lt 1 ]
	then
		echo "BTN0" > /dev/console
		sync
#		reboot
	elif [ "$SEEN" -gt 5 ]
	then
		echo "FACTORY BTN0" > /dev/console
		jffs2reset -y && reboot &
	fi
;;
esac

return 0
